### ISSUE TITLE
Project question

### ISSUE THREAD

**Issue by Roet-Ivar** [Random06457/rpi4-gpu-bare-metal-examples#1]
Random first of all, I'm so sorry for doing this, but I haven't found any other way to contact you :( 
Is there any chance you'd share or open source your CS-project of the[ wii-u-boot-title-editor](https://github.com/Random06457/Wii-U-Title-Boot-Editor)?
I really like that tool and would love to continue adding some features to it. 
Again, I'm sorry for taking this route!

**Comment by Random06457** [comment]
This issue is unrelated to this project so I'm going to close it.
Please find my answer for your request [here](https://github.com/Random06457/Wii-U-Title-Boot-Editor/issues/1#issuecomment-1678265403).
