### ISSUE TITLE
Strange frame buffer creation issue

### ISSUE THREAD

**Issue by makuto** [Random06457/rpi4-gpu-bare-metal-examples#3]
Hi,

When attempting to run this project, I appear to be failing to get a valid framebuffer. I was able to step debug and found the `videocore::SetVirtualWH` to be returning a strange response. The request is for 1920x1080, but the response appears to be 2x2, and still returns success (or at least, the assert does not seem to trigger).

The SetPhysicalWH message returns 1920x1080 as expected.

The end result is a giant white square on the screen. I tried just overwriting the width and height to always be 1920x1080, regardless of what the mailbox returns. This results in a single black apparently anti-aliased/blended corner in the white rectangle.

I have admittedly made some modifications to the library, but nothing touching the mailbox.

**Comment by Random06457** [comment]
Hi, I would not have expected this part to fail as it's essentially a copy and paste of every single RPI baremetal repo that uses the screen.

The first thing that comes to mind is that your setup somehow differs from mine in a way that makes this code not work.

Maybe try to check if you have the same issue with a different rpi baremetal repo. E.g. https://github.com/isometimes/rpi4-osdev/blob/master/part5-framebuffer/fb.c#L8

The second thing I can think of is if the boot config or firmware revision is different. For that, I'll try to pin the exact version of the firmware blob I'm using and send my config.txt file tonight (utc+1).

**Comment by makuto** [comment]
It could be a firmware difference, given my firmware is probably a year newer than yours. Your config.txt would be great to have!

**Comment by Random06457** [comment]
Here is the firmware that I'm using as well as my config.txt file:
[firmware.zip](https://github.com/Random06457/rpi4-gpu-bare-metal-examples/files/13430357/firmware.zip)

**Comment by makuto** [comment]
It was the `config.txt` that was the issue. My guess is that this line is required:
```
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
dtoverlay=vc4-fkms-v3d
```
It would be helpful if you checked in the `config.txt` for future reference.
Thanks for sending the firmware! I am excited to play with this more. I would also be interested in exactly what your modifications to the kernel were that let you see what Linux was sending to the GPU.

**Comment by Random06457** [comment]
I pushed the changes I made to linux here: https://github.com/Random06457/linux/commits/v3d-test
Please note that I just pushed what I found on my hard drive but I didn't test it so it may not even compile

**Comment by makuto** [comment]
Thank you!

**Comment by makuto** [comment]
A note for future searchers:
The following is a trimmed down list of firmware; there may be even more files that can be removed, but I know at least these work:
```
bcm2711-rpi-4-b.dtb
LICENCE.broadcom
bootcode.bin
start.elf
fixup.dat
start4.elf
fixup4.dat
start_cd.elf
fixup_cd.dat
start4cd.elf
fixup4cd.dat
armstub8-rpi4.bin
kernel8.img
overlays/vc4-fkms-v3d.dtbo
overlays/vc4-fkms-v3d-pi4.dtbo
overlays/vc4-kms-v3d-pi4.dtbo
overlays/vc4-kms-v3d-pi5.dtbo
overlays/vc4-kms-v3d.dtbo
```
These are available [here](https://github.com/raspberrypi/firmware/tree/master/boot) and can be downloaded via a script [like this](https://macoy.me/code/macoy/rpi-system/src/branch/master/DownloadFirmware.sh). Don't try to download the whole raspberrypi/firmware, it is enormous.
